### ISSUE TITLE
Font size, window size optimisation needed

### ISSUE THREAD

**Issue by tacurran** [jfcurran/execpresentation#4]
@jfcurran on the "leadership" slide:
1. Text flow not easy on the eyes
2. The last point is not part of the list, its a motto - make it the same colour as the quotes

The new version is for the following event:
15H00 -  15H30
"Deutsche Börse and the Cloud Computing"
Thomas Curran
Deutsche Börse

[20170530- AWS Event in Luxembourg ­ agenda.pdf](https://github.com/jfcurran/execpresentation/files/1037608/20170530-.AWS.Event.in.Luxembourg.agenda.pdf)

 
https://www.eventbrite.com/e/aws-financial-services-tech-day-luxembourg-tickets-34303285049

**Comment by jfcurran** [comment]
Hey Thomas!

Muss das bis heute um 15:00 geschehen? :O Das ist unmöglich, heute nacht
ist das schnellst mögliche.
Wie gehts sonst? hier alles gut, ich muss viel für klausuren lernen 😅 und
gestern ist mein handy kaputt gegangen... aber donnerstag krieg ich ein
neues :)
Hatte das mit Imarum eigentlich geklappt? Was war da der letzte stand?

Liebe Grüße

**Comment by tacurran** [comment]
@jfcurran  can you close this issue by 6.6.2017?

**Comment by jfcurran** [comment]
Is every point resolved? @tacurran
